name: 'GZHU Auto Clock In'

on:
  schedule:
    - cron: '0 23 * * *' # Clock in at 7:00 CST everyday.
  workflow_dispatch:  # manually dispatch
    inputs:
      delays:
        description: '(Optional)Delayed time'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@main
      
      - name: 'Set up Python'
        uses: actions/setup-python@main
        with:
          python-version: '3.x'

      - name: 'Install requirements'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Wait ${{ github.event.inputs.delays }}
        if: ${{ github.event.inputs.delays != '' }}
        run: sleep ${{ github.event.inputs.delays }}

      - name: 'Perform clock in'
        env:
          STUID: ${{ secrets.STUID }}
          STUPWD: ${{ secrets.STUPWD }}
          TZ: Asia/Shanghai
        run: python run_action.py
